# Generated by Django 4.2.2 on 2023-06-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=200)),
                (
                    "geslacht",
                    models.CharField(
                        choices=[
                            ("Man", "Mannelijk"),
                            ("Vrouw", "Vrouwelijk"),
                            ("Onbekend", "Onbekend"),
                        ],
                        default="Onbekend",
                        max_length=200,
                    ),
                ),
                ("foto", models.ImageField(null=True, upload_to="photos/%Y/%m/%d")),
            ],
        ),
        migrations.CreateModel(
            name="Kattensoort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soort", models.CharField(max_length=200)),
            ],
        ),
    ]
