# Generated by Django 4.2.2 on 2023-06-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalogus", "0002_kat_soort_alter_kattensoort_soort"),
    ]

    operations = [
        migrations.AddField(
            model_name="kat",
            name="kanBijHonden",
            field=models.CharField(
                choices=[("Ja", "Ja"), ("Nee", "Nee"), ("Onbekend", "Onbekend")],
                default="Onbekend",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="kat",
            name="kanBijKatten",
            field=models.CharField(
                choices=[("Ja", "Ja"), ("Nee", "Nee"), ("Onbekend", "Onbekend")],
                default="Onbekend",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="kat",
            name="kanBijKinderen",
            field=models.CharField(
                choices=[("Ja", "Ja"), ("Nee", "Nee"), ("Onbekend", "Onbekend")],
                default="Onbekend",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="kat",
            name="leeftijd",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="kat",
            name="moetNaarBuiten",
            field=models.CharField(
                choices=[("Ja", "Ja"), ("Nee", "Nee"), ("Onbekend", "Onbekend")],
                default="Onbekend",
                max_length=200,
            ),
        ),
    ]
