# Generated by Django 4.2.2 on 2023-06-29 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "katalogus",
            "0003_kat_kanbijhonden_kat_kanbijkatten_kat_kanbijkinderen_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="kat",
            name="beschikbaarVanaf",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="kat",
            name="locatie",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="kat",
            name="specialeZorg",
            field=models.CharField(
                choices=[
                    ("Nee", "Nee"),
                    ("Onbekend", "Onbekend"),
                    ("Blind", "Blind"),
                    ("Doof", "Doof"),
                    ("Medicijnen", "Medicijnen"),
                    ("Behandeling gedragsproblemen", "Behandeling gedragsproblemen"),
                    ("Dieetvoer", "Dieetvoer"),
                ],
                default="Onbekend",
                max_length=200,
            ),
        ),
    ]
