# Generated by Django 3.2 on 2023-07-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalogus', '0004_kat_beschikbaarvanaf_kat_locatie_kat_specialezorg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kat',
            name='geslacht',
            field=models.CharField(choices=[('Mannelijk', 'Mannelijk'), ('Vrouwelijk', 'Vrouwelijk'), ('Onbekend', 'Onbekend')], default='Onbekend', max_length=200),
        ),
    ]
