# Generated by Django 3.2 on 2023-07-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalogus', '0005_alter_kat_geslacht'),
    ]

    operations = [
        migrations.AddField(
            model_name='kat',
            name='beschrijving',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
