# Generated by Django 3.2 on 2023-07-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalogus', '0006_kat_beschrijving'),
    ]

    operations = [
        migrations.AddField(
            model_name='kat',
            name='gecastreerd',
            field=models.CharField(choices=[('Ja', 'Ja'), ('Nee', 'Nee'), ('Onbekend', 'Onbekend')], default='Onbekend', max_length=200),
        ),
    ]
